Given an array of integers, return indices of the two numbers such that they add up to a specific target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

Example:

Given nums = [2, 7, 11, 15], target = 9,

Because nums[0] + nums[1] = 2 + 7 = 9,
return [0, 1].

In [50]:
# from web
class Subject():
    def twosum(self, nums, target):
        lookup = {}
        for cnt, num in enumerate(nums):
            if target - num in lookup:
                return lookup[target-num], cnt
            lookup[num] = cnt 

nums = [2, 7, 11, 15]
target = 9
twosum(nums, target)

{0: 2, 1: 7}

In [34]:
# my solution
def twosum(nums, target):
    solution = {}
    for i,n in enumerate(nums):
        if (target - n) in nums:
            solution[i] = n
    return solution

In [35]:
nums = [2, 7, 11, 15]
target = 9
twosum(nums, target)

{0: 2, 1: 7}

NO IDEA:
You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order and each of their nodes contain a single digit. Add the two numbers and return it as a linked list.

You may assume the two numbers do not contain any leading zero, except the number 0 itself.

In [39]:
# def lengthOfLongestSubstring(word):
#     n = len(word)
#     longest = 0
#     for i in range(n):
#         seen = set()
#         for j in range(i, n):
#             if word[j] in seen: break
#             seen.add(word[j])
#         longest = max(len(seen), longest)
#     return longest

In [41]:
lengthOfLongestSubstring('abcad')

4

Count ways to express a number as sum of consecutive numbers
Given a number N, find the number of ways to represent this number as a sum of 2 or more consecutive natural numbers.

## Find minimum difference between any two elements | Set 2

In [65]:
import numpy as np
import itertools
import time
def min_abs_diff(values):
    start_time = time.time()
    #print('values: {}'.format(values))
    combinations = set(list(itertools.permutations(values, 2)))
    results = []
    for i in combinations:
        results.append(abs(i[0] - i[1]))
    print('the function took {:5f} to run'.format(time.time() - start_time))
    return(min(set(results)))
values = np.array([9,11,21,23])
print(min_abs_diff(values))

the function took 0.000026 to run
2


### Number of subsets with zero sum

In [66]:
import numpy as np
import itertools
values = np.array([2,2,-8,-4,4])

#print(sum(values))

#print(list(itertools.combinations(values,2)))
combinations = []
def subset_sum_0(values):
    '''comment'''
    for i in range (0,values.shape[0] + 1):
        combinations.append(list(itertools.combinations(values,i)))
    items = [s for x in combinations for s in x] # to concatenate lists into one long list.
    cnt = 0
    for c in items:
        if sum(c) == 0:
            cnt += 1
    return cnt


print(subset_sum_0(values))

4


### Pair with largest sum which is less than K in the array
https://www.geeksforgeeks.org/pair-with-largest-sum-which-is-less-than-k-in-the-array/

In [78]:
import itertools
import numpy as np
import time


values =np.array([5, 20, 110, 100, 10])
dictionary = {}
k = 120
c = 2 
def max_sum_pair(values,k,c):
    start_time = time.time()
    combinations = list(itertools.combinations(values,c))
    for pairs in combinations:
        if sum(pairs) < k:
            score = pairs[0] + pairs[1]
            dictionary = {'values':pairs,'sum':score}
    print('it took {:5f}'.format(time.time() - start_time))
    return dictionary

        
print(max_sum_pair(values,k,c))

it took 0.000025
{'values': (100, 10), 'sum': 110}


### Greatest contiguous sub-array of size K
Given an array arr[] of integers and an integer K, the task is to find the greatest contiguous sub-array of size K. Sub-array X is said to be greater than sub-array Y if the first non-matching element in both the sub-arrays has a greater value in X than in Y.

In [109]:
import numpy as np

def possible_subarrays(values,k):
    i = 0
    list_values = []
    while i < len(values) + 1:
        if len(values[i:k]) > 1 :
            list_values.append(values[i:k].tolist())
        i +=1
        k+=1
    
    a = []
    for val in list_values:
        a.append(val[0])
    result = list_values[a.index(max(a))]
    return result

[4, 3, 2, 5]

In [110]:
values = np.array([1, 4, 3, 2, 5])
k = 4
possible_subarrays(values,k)

[4, 3, 2, 5]

In [111]:
values = np.array([1, 9, 2, 7, 9, 3])
k = 3
possible_subarrays(values,k)

[9, 2, 7]

### Find the smallest positive number missing from an unsorted array | Set 3
Given an unsorted array with both positive and negative elements. The task is to find the smallest positive number missing from the array.

In [115]:
import numpy as np
def minint_missvalue(values):
    positive_values = values[values>0]
    sort_values = np.sort(positive_values) # sort an array wit np.array . if a list, list.sort()
    possible_values = []
    for i in range(min(sort_values),max(sort_values)):
        if (i not in sort_values): # check if an item is in a list, if i not in values
            possible_values.append(i)

    return min(possible_values)

In [119]:
values = np.array([1,5,5,5,2])
print(minint_missvalue(values))
values_2 = np.array([2, 3, 7, 6, 8, -1, -10, 15])
print(minint_missvalue(values_2))

3
4


### Find the element that appears once

In [15]:
import numpy as np
import pandas as pd

def min_count(values):
    unique_values, counts = np.unique(values, return_counts = True)
    dictionary = dict(zip(unique_values, counts))
    return dictionary

def get_dict_key(val,dictionary):
        for key,value in dictionary.items():
            if val == value:
                return key
            

In [16]:
get_dict_key(min(dictionary.values()),dictionary)
get_dict_key(1,dictionary)

2

### Determining the Most Frequently Occurring Items in a Sequence of integers, words. Also for arrays. 
using:
#### from collections import Counter

In [23]:
words = [   'look', 'into', 'my', 'eyes', 'look', 'into', 'my', 'eyes',   'the', 'eyes', 'the', 'eyes', 'the', 'eyes', 'not', 'around', 'the',   'eyes', "don't", 'look', 'around', 'the', 'eyes', 'look', 'into',   'my', 'eyes', "you're", 'under' ]
from collections import Counter
word_counts = Counter(words)
top_three = word_counts.most_common(3)
print(top_three) 

print(word_counts['into'])

# if I add additional words
additional_words = ['into', 'mywords', 'eyes']

# use .update(new_words)
word_counts.update(additional_words)
print(word_counts)

### or also ###
print(10*'%')
for word in additional_words:
    word_counts[word] += 1
print(word_counts)
print(10*'%')
## also operations like
a = Counter(['ciao','io','sono'])
b = Counter(['ciao','tu','sono'])
print(a-b)
print(2*'%')
print(a+b)



[('eyes', 8), ('the', 5), ('look', 4)]
3
Counter({'eyes': 9, 'the': 5, 'look': 4, 'into': 4, 'my': 3, 'around': 2, 'not': 1, "don't": 1, "you're": 1, 'under': 1, 'mywords': 1})
%%%%%%%%%%
Counter({'eyes': 10, 'into': 5, 'the': 5, 'look': 4, 'my': 3, 'around': 2, 'mywords': 2, 'not': 1, "don't": 1, "you're": 1, 'under': 1})
%%%%%%%%%%
Counter({'io': 1})
%%
Counter({'ciao': 2, 'sono': 2, 'io': 1, 'tu': 1})


In [13]:
## it words with numpy as way
import numpy as np
from collections import Counter
values = np.array([1,4,4,4,2,6,66,599])
print(values)
count_values = Counter(values)
print(count_values)

[  1   4   4   4   2   6  66 599]
Counter({4: 3, 1: 1, 2: 1, 6: 1, 66: 1, 599: 1})


In [14]:
values = np.array([1,4,4,4,2,6,66,599])
count_values = Counter(values)
def find_key(value,dictionary):
    for key,val in dictionary.items():
        if val == value:
            return key

print(find_key(3,dict(count_values)))

4


### Find uncommon characters of the two strings | Set 2

In [71]:
def uncommon_characters(string1,string2):
    c1 = []
    c2 = []
    result1 = []
    result2 = []
    for i in string1:
        c1.append(i)
    for t in string2:
        c2.append(t)

    result = [set(c1) - set(c2), set(c2) - set(c1)]
    result = [i for x in result for i in x]
    result.sort()
    return result

In [72]:
s  = uncommon_characters('abadpq', 'cabr')
s

['c', 'd', 'p', 'q', 'r']

## list.append(..), list.pop(), list.leftappend(..)


In [1]:
from collections import deque

q = deque(maxlen = 2)

q.append(1)
q.append(2)
print(q)
q.append(3)
print(q)

q.appendleft(5)
print(q)

q.pop()
print(q)
    
q.append(10)
print(q)
q.popleft()
print(q)

deque([1, 2], maxlen=2)
deque([2, 3], maxlen=2)
deque([5, 2], maxlen=2)
deque([5], maxlen=2)
deque([5, 10], maxlen=2)
deque([10], maxlen=2)


### Finding the Largest or Smallest N Items 
using:
#### import heapq 

In [2]:
import heapq

nums = [1, 8, 2, 23, 7, -4, 18, 23, 42, 37, 2] 
print(heapq.nlargest(3, nums))  # Prints [42, 37, 23]
print(heapq.nsmallest(3, nums)) # Prints [-4, 1, 2]

nums.sort(key = int, reverse = True)
print(nums[:3])

print(heapq.nsmallest(1, nums))

[42, 37, 23]
[-4, 1, 2]
[42, 37, 23]
[-4]


In [4]:
portfolio = [   {'name': 'IBM', 'shares': 100, 'price': 91.1},
             {'name': 'AAPL', 'shares': 50, 'price': 543.22},
             {'name': 'FB', 'shares': 200, 'price': 21.09}, 
             {'name': 'HPQ', 'shares': 35, 'price': 31.75},
             {'name': 'YHOO', 'shares': 45, 'price': 16.35},  
             {'name': 'ACME', 'shares': 75, 'price': 115.65} ]

heapq.nsmallest(3, portfolio, key=lambda s: s['price'])

[{'name': 'YHOO', 'price': 16.35, 'shares': 45},
 {'name': 'FB', 'price': 21.09, 'shares': 200},
 {'name': 'HPQ', 'price': 31.75, 'shares': 35}]

## another way to create dictionary
#### defaultdict(list)
#### defaultdict(lambda: '')

In [2]:
from collections import defaultdict

d = defaultdict(list)
d['a'].append(1)
d['a'].append(2)
d['b'].append(4)
print(d)

d = defaultdict(set)

d['a'].add(1)
d['a'].add(2)
d['b'].add(4)
print(d)

defaultdict(<class 'list'>, {'a': [1, 2], 'b': [4]})
defaultdict(<class 'set'>, {'a': {1, 2}, 'b': {4}})


In [17]:
from collections import  OrderedDict
dictionary = defaultdict(list)
dictionary['a'].append(2)
dictionary['d'].append(4)
dictionary['b'].append(5)
print(dictionary)
sorted(dictionary.items(), key = lambda x: x[0])


defaultdict(<class 'list'>, {'a': [2], 'd': [4], 'b': [5]})


[('a', [2]), ('b', [5]), ('d', [4])]

In [189]:
from collections import defaultdict
t = defaultdict(lambda: 'NaN')
t['a'] = 4
t.update({'c':3})
print(t)
t['g']

defaultdict(<function <lambda> at 0x110585488>, {'a': 4, 'c': 3})


'NaN'

In [176]:
city_dict = defaultdict(list)
for state,city in city_list:
    city_dict[state].append(city)
    
city_dict

defaultdict(list,
            {'TX': ['Austin', 'Houston', 'Dallas'],
             'NY': ['Albany', 'Syracuse', 'Buffalo', 'Rochester'],
             'CA': ['Sacramento', 'Palo Alto'],
             'GA': ['Atlanta']})

### use zip to calculate min,max, sort values in a dictionary

In [6]:
prices = {   'ACME': 45.23,   'AAPL': 612.78,   'IBM': 205.55,   'HPQ': 37.20,   'FB': 10.75 }
prices

{'AAPL': 612.78, 'ACME': 45.23, 'FB': 10.75, 'HPQ': 37.2, 'IBM': 205.55}

In [7]:
min_values = min(zip(prices.values(),prices.keys()))
min_values

(10.75, 'FB')

In [8]:
max_values = min(zip(prices.keys(),prices.values()))
max_values

('AAPL', 612.78)

In [9]:
sorted_values = sorted(zip(prices.values(),prices.keys()))
sorted_values

[(10.75, 'FB'),
 (37.2, 'HPQ'),
 (45.23, 'ACME'),
 (205.55, 'IBM'),
 (612.78, 'AAPL')]

In [15]:
prices_names = zip(prices.values(),prices.keys())
print(max(prices_names))
print(max(prices))
print(max(prices.values()))

(612.78, 'AAPL')
IBM
612.78


### to get max/min key or value in a dictionary

In [16]:
print(min(prices, key=lambda k: prices[k]))
print(prices[min(prices, key=lambda k: prices[k])])

FB
10.75


### find differences or commonalities in dictionaries 

In [3]:
a = {'x':2, 'y':2}
b= {'x':2,'r':4}
print(a)
print(b)
# Find keys in common
print(a.keys() & b.keys())
# Find keys in a that are not in b
print(a.keys() - b.keys())
# Find (key,value) pairs in common
print(a.items() & b.items()) 

{'x': 2, 'y': 2}
{'x': 2, 'r': 4}
{'x'}
{'y'}
{('x', 2)}


### using slice

In [7]:
items = [1,2,5,4,6]
a = slice(2,4)
print(items[a])
b = slice(1,4,2)
print(b.start)
print(b.stop)
print(b.step)

[5, 4]
1
4
2


###  Sorting a List of Dictionaries by a Common Key 
 using:
#### from opereator import itemgetter
or without itemgetter, but using
#### sorted ( dict_name, key = lambda x: x[''])

In [26]:
rows = [{'fname': 'Brian', 'lname': 'Jones', 'uid': 1003},
        {'fname': 'David', 'lname': 'Beazley', 'uid': 1002},
        {'fname': 'John', 'lname': 'Cleese', 'uid': 1001},
        {'fname': 'Big', 'lname': 'Jones', 'uid': 1004} ]

from operator import itemgetter
sort_fame = sorted(rows, key=itemgetter('fname'))
print(sort_fame)
print(10*'%')
sort_multi_var = sorted(rows, key = itemgetter('fname','lname'))
print(sort_multi_var)

# without itemgetter, but using sorted ( dict_name, key = lambda x: x[''])
print('using lambda')
rows_by_fname = sorted(rows, key=lambda r: r['fname'])
print(rows_by_fname)

[{'fname': 'Big', 'lname': 'Jones', 'uid': 1004}, {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003}, {'fname': 'David', 'lname': 'Beazley', 'uid': 1002}, {'fname': 'John', 'lname': 'Cleese', 'uid': 1001}]
%%%%%%%%%%
[{'fname': 'Big', 'lname': 'Jones', 'uid': 1004}, {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003}, {'fname': 'David', 'lname': 'Beazley', 'uid': 1002}, {'fname': 'John', 'lname': 'Cleese', 'uid': 1001}]
using lambda
[{'fname': 'Big', 'lname': 'Jones', 'uid': 1004}, {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003}, {'fname': 'David', 'lname': 'Beazley', 'uid': 1002}, {'fname': 'John', 'lname': 'Cleese', 'uid': 1001}]


### Filtering a sequence of items
#### from itertools import compress

In [27]:
from itertools import compress
address = ['via terminio', 'casoria','Napoli']
numeri= [1,3,-1]

number_pos  = [n >0 for n in numeri]

print(list(compress(address,number_pos)))

['via terminio', 'casoria']


### Subset of dictionary
using
#### dictionary comprehension

In [30]:
prices = {   'ACME': 45.23,   'AAPL': 612.78,   'IBM': 205.55,   'HPQ': 37.20,   'FB': 10.75 }
{key:value for key,value in prices.items() if value > 200}

{'AAPL': 612.78, 'IBM': 205.55}

In [33]:
tech_names = { 'AAPL', 'IBM', 'HPQ', 'MSFT' }
{ key:value for key,value in prices.items() if key in tech_names }

{'AAPL': 612.78, 'IBM': 205.55, 'HPQ': 37.2}

### Lookup across dictionaries
using:
#### from collections import ChainMap

In [48]:
a = {'x': 1, 'z': 3 }
b = {'y': 2, 'z': 4 }
from collections import ChainMap 
c = ChainMap(a,b) 
print(c['z'])
print(list(c.keys()))
print(list(c.values()))
print(list(c.items()))

3
['y', 'x', 'z']
[2, 1, 3]
[('y', 2), ('x', 1), ('z', 3)]


In [51]:
c

ChainMap({'z': 3}, {'y': 2, 'z': 4})

### merging dictionary using dict1.update(dict2)

In [56]:
a = {'c':4}
b = {'b':3}
a.update(b)
a

{'c': 4, 'b': 3}

In [58]:
sorted(a)

['b', 'c']

In [27]:
from itertools import combinations, permutations
a = list([1,4,5])
print(list(combinations(a,2)))
print(list(permutations(a,2)))

[(1, 4), (1, 5), (4, 5)]
[(1, 4), (1, 5), (4, 1), (4, 5), (5, 1), (5, 4)]


In [309]:
from itertools import combinations, combinations_with_replacement
values = [1,2,3]
print(list(combinations_with_replacement(values,2)))
print(list(combinations(values,2)))

[(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]
[(1, 2), (1, 3), (2, 3)]


In [35]:
import numpy as np
values = np.array([[1,2,2,4,2,4,3], [1,4,3,6,5,4,6]])
values

array([[1, 2, 2, 4, 2, 4, 3],
       [1, 4, 3, 6, 5, 4, 6]])

In [62]:
s = np.argsort(-values,1)[0][:5]
s

array([3, 5, 6, 1, 2])

In [58]:
import torch
t = torch.tensor(s)
t

tensor([3, 5, 6, 1, 2])

In [61]:
t[:2]

tensor([3, 5])

In [66]:
from itertools import compress
values = [1,-2,-4,3]
names = ['giorgio','antonio','p','mondauto']
values_pos = [n>0 for n in values]
list(compress(names,values_pos))

['giorgio', 'mondauto']

In [72]:
from itertools import combinations, permutations
print(list(combinations(values,2)))
print(10*'%')
print(list(permutations(values,2)))

[(1, -2), (1, -4), (1, 3), (-2, -4), (-2, 3), (-4, 3)]
%%%%%%%%%%
[(1, -2), (1, -4), (1, 3), (-2, 1), (-2, -4), (-2, 3), (-4, 1), (-4, -2), (-4, 3), (3, 1), (3, -2), (3, -4)]


In [75]:
from collections import Counter
names.append('p')
names.append('mondauto')
names

['giorgio', 'antonio', 'p', 'mondauto', 'p', 'mondauto', 'p', 'mondauto']

In [88]:
word_counter = Counter(names)
word_counter.most_common(1)

[('p', 3)]

In [106]:
from collections import deque

values = deque(maxlen = 2)
values.append(1)
values.append(2)
values

deque([1, 2])

In [128]:
from collections import ChainMap
a = {'a': [1,2]}
b = {'s': 4}

In [129]:
t = ChainMap(a,b)
t

ChainMap({'a': [1, 2]}, {'s': 4})

In [126]:
a.update(b)
a

{'a': [1, 2], 's': 4}

In [134]:
a

{'a': [1, 2], 'd': [1, 4, 3], 'b': 2, 'z': [4, 3]}

In [145]:
from collections import OrderedDict
x = OrderedDict(sorted(a.items(),key = lambda x: x[0]))
print(x)
print(type(x))

OrderedDict([('a', [1, 2]), ('b', 2), ('d', [1, 4, 3]), ('z', [4, 3])])
<class 'collections.OrderedDict'>


In [146]:
y = sorted(a.items(),key = lambda x: x[0])
print(y)
print(type(y))

[('a', [1, 2]), ('b', 2), ('d', [1, 4, 3]), ('z', [4, 3])]
<class 'list'>


In [186]:
from collections import defaultdict
t = defaultdict(lambda: 'NaN')
t['a'] = 4
t.update({'c':3})

In [188]:
t['b']

'NaN'

In [1]:
city_list = [('TX','Austin'), ('TX','Houston'),
             ('NY','Albany'), ('NY', 'Syracuse'),
             ('NY', 'Buffalo'), ('NY', 'Rochester'),
             ('TX', 'Dallas'), ('CA','Sacramento'),
             ('CA', 'Palo Alto'), ('GA', 'Atlanta')]
city_list

[('TX', 'Austin'),
 ('TX', 'Houston'),
 ('NY', 'Albany'),
 ('NY', 'Syracuse'),
 ('NY', 'Buffalo'),
 ('NY', 'Rochester'),
 ('TX', 'Dallas'),
 ('CA', 'Sacramento'),
 ('CA', 'Palo Alto'),
 ('GA', 'Atlanta')]

In [181]:
city_dict = defaultdict(list)
for state,city in city_list:
    city_dict[state].append(city)
    
city_dict

defaultdict(list,
            {'TX': ['Austin', 'Houston', 'Dallas'],
             'NY': ['Albany', 'Syracuse', 'Buffalo', 'Rochester'],
             'CA': ['Sacramento', 'Palo Alto'],
             'GA': ['Atlanta']})

In [185]:
sorted(city_dict.items(), key = lambda x: x[0])

[('CA', ['Sacramento', 'Palo Alto']),
 ('GA', ['Atlanta']),
 ('NY', ['Albany', 'Syracuse', 'Buffalo', 'Rochester']),
 ('TX', ['Austin', 'Houston', 'Dallas'])]

In [29]:
library = [('antonio','26'),('jina','30'), ('giorgio','45')]
library

[('antonio', '26'), ('jina', '30'), ('giorgio', '45')]

In [30]:
s = dict(library)
s

{'antonio': '26', 'jina': '30', 'giorgio': '45'}

In [33]:
from collections import defaultdict
library_dict = defaultdict(list)
for name,age in library:
    library_dict[name]= age

In [67]:
library_dict

defaultdict(list, {'antonio': '26', 'jina': '30', 'giorgio': '45'})

In [101]:
import heapq
import numpy as np
values = np.array([1,10,19,2,2])
values

array([ 1, 10, 19,  2,  2])

In [55]:
heapq.nlargest(2,values)

[19, 10]

In [68]:
def get_key(val,dictionary):
    for key, value in dictionary.items():
        if val == value:
            return key
get_key('26',library_dict)

'antonio'

### Text Manipulation

In [87]:
import re
line = 'asdf fjdk; afed, fjek, asdf, foo'

In [93]:
fields = re.split(r'[;,\s]*\s',line)  #*/s means derivatives of /s
fields

['asdf', 'fjdk', 'afed', 'fjek', 'asdf', 'foo']

In [96]:
fields[::2] # 1-3-5

['asdf', 'afed', 'asdf']

In [97]:
fields[::3] #1 - 4 - 7

['asdf', 'fjek']

In [100]:
fields[1::2] + ['']

['fjdk', 'fjek', 'foo', '']

In [124]:
filename = 'claimsdata.txt'
filename.startswith('c')
filename.endswith('.txt')

True

### Iterator

In [230]:
items = [1, 2, 3]
it = iter(items)
next(it)

1

In [231]:
next(it)

2

In [232]:
next(it)

3

In [248]:
def frange(start,stop,increment):
    x = start
    while x < stop:
        yield x
        x+= increment

In [249]:
for i in frange(1,5,0.5):
    print(i)

1
1.5
2.0
2.5
3.0
3.5
4.0
4.5


In [250]:
list(frange(1,5,0.5))

[1, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [261]:
def countdown(n):
    print('start')
    while n>0:
        yield n
        n -= 1
    print('go')

In [277]:
c = countdown(5)
next(c)

start


5

In [278]:
next(c)

4

In [279]:
next(c)

3

In [284]:
a = [1,2,3,4]
for i in reversed(a): # reversed 
    print(i)

4
3
2
1


### from itertools import islice

In [303]:
from itertools import islice
items = ['a', 'b', 'c', 1, 4, 10, 15]
for x in islice(items, 0, None):
    print(x)

a
b
c
1
4
10
15


In [304]:
values = np.array([1,2,4,5,6,5,4,3])
for i in islice(values,4,len(values)): # islice
    print(i)

6
5
4
3


### enumerate (values, starting_point)

In [332]:
from collections import defaultdict
items = ['a','c','b']
# print(items)
dictionary = defaultdict()
for idx,item in enumerate(items,0):
    dictionary[item]=idx
    

In [333]:
dictionary

defaultdict(None, {'a': 0, 'c': 1, 'b': 2})

In [334]:
sorted(dictionary.items(), key = lambda x:x[0])

[('a', 0), ('b', 2), ('c', 1)]

#### list of tuples with enumerate

In [341]:
data = [ (1, 2), (3, 4), (5, 6), (7, 8) ]
data

[(1, 2), (3, 4), (5, 6), (7, 8)]

In [342]:
data_dict = defaultdict()
for n, (x,y) in enumerate(data):
    data_dict[(x,y)] = n


In [343]:
data_dict

defaultdict(None, {(1, 2): 0, (3, 4): 1, (5, 6): 2, (7, 8): 3})

### Iterating Over Multiple Sequences Simultaneously with zip()

In [353]:
items = ['a', 'd', 'f' , 'b']
values = [1,55,4,3]
dict_data = defaultdict()
for key,idx in zip(items,values):
    dict_data[key] = idx

In [356]:
print(dict_data)
print(sorted(dict_data.items(), key = lambda x: x[0]))

defaultdict(None, {'a': 1, 'd': 55, 'f': 4, 'b': 3})
[('a', 1), ('b', 3), ('d', 55), ('f', 4)]


In [359]:
# to repeat compress
from itertools import compress
values_tr = [n>3 for n in values]
list(compress(items,values_tr))

['d', 'f']

#### zip with dict

In [374]:
headers = ['name', 'shares', 'price']
values = [11, 100, 490.1]
dict_data = dict(zip(headers,values))
dict_data

{'name': 11, 'shares': 100, 'price': 490.1}

### from itertools import chain

In [377]:
from itertools import chain
headers = ['name', 'shares', 'price']
values = [11, 100, 490.1]
list(chain(headers,values))
#headers + values but chain workes better and faster

['name', 'shares', 'price', 11, 100, 490.1]

In [395]:
[i.tolist() for x in np.unique(values, return_counts= True) for i in x]

[11.0, 100.0, 490.1, 1, 1, 1]

In [400]:
a = [i.tolist() for i in np.unique(values, return_counts= True)][0]
b = [i.tolist() for i in np.unique(values, return_counts= True)][1]
dict(zip(a,b))

{11.0: 1, 100.0: 1, 490.1: 1}

In [403]:
import heapq
heapq.nlargest(1,values)

[490.1]

In [406]:
list(heapq.merge(a,b))

[1, 1, 1, 11.0, 100.0, 490.1]

In [408]:
list(chain(a,b))

[11.0, 100.0, 490.1, 1, 1, 1]

In [413]:
values = [1,43,55,2]
keys = ['a','b','z','c']
val_dict = dict(zip(keys,values))

In [430]:
for t, (key,val) in enumerate(zip(keys,values)):
    print(t,(key,val))

0 ('a', 1)
1 ('b', 43)
2 ('z', 55)
3 ('c', 2)


In [434]:
from itertools import *
from collections import *

In [435]:
values = [1,43,55,2]
keys = ['a','b','z','c']

In [438]:
bool_values = [n<43 for n in values]
list(compress(keys,bool_values))

['a', 'c']

In [440]:
list(combinations(keys,2))

[('a', 'b'), ('a', 'z'), ('a', 'c'), ('b', 'z'), ('b', 'c'), ('z', 'c')]

In [442]:
list(combinations_with_replacement(keys,2))

10

In [451]:
len(list(permutations(keys,2)))

12

In [460]:
list(product(keys,repeat = 2))

[('a', 'a'),
 ('a', 'b'),
 ('a', 'z'),
 ('a', 'c'),
 ('b', 'a'),
 ('b', 'b'),
 ('b', 'z'),
 ('b', 'c'),
 ('z', 'a'),
 ('z', 'b'),
 ('z', 'z'),
 ('z', 'c'),
 ('c', 'a'),
 ('c', 'b'),
 ('c', 'z'),
 ('c', 'c')]

In [464]:
list(islice(keys,4))

['a', 'b', 'z', 'c']

In [470]:
key_count = Counter(keys)
key_count

Counter({'a': 1, 'b': 1, 'z': 1, 'c': 1})

In [481]:
a = deque(maxlen = 2)
a.append(2)
a.append(3)
a.appendleft(4)
a.pop()
a

deque([4])

In [485]:
sorted(key_count.items(), key = lambda x: x[0])

['a', 'b', 'c', 'z']

In [494]:
dict_list = defaultdict(list)
for key,val in zip(keys,values):
    dict_list[key] = val
dict_list

defaultdict(list, {'a': 1, 'b': 43, 'z': 55, 'c': 2})

In [495]:
b=ChainMap(dict_list,key_count)

In [496]:
b.items()

ItemsView(ChainMap(defaultdict(<class 'list'>, {'a': 1, 'b': 43, 'z': 55, 'c': 2}), Counter({'a': 1, 'b': 1, 'z': 1, 'c': 1})))

In [525]:
values = ['a','a','a','b','c','b','c','c','a']
count_unique = np.unique(np.array(values),return_counts = True)


In [526]:
dictionary = dict()
for key,val in zip(count_unique[0].tolist(),count_unique[1].tolist()):
    dictionary[key] = val
dictionary

{'a': 4, 'b': 2, 'c': 3}

In [539]:
def get_key(key_input,dict_g):
    for key,val in dict_g.items():
        if key == key_input:
            return val

In [540]:
get_key('a',dictionary)

4